services:
  - type: web
    name: saha-takvim
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && flask db upgrade && flask seed-admin
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: saha-db
          property: connectionString
      - key: DEFAULT_ADMIN_USERNAME
        value: admin
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false

databases:
  - name: saha-db
    plan: starter
